name: VoidReader
options:
  bundleIdPrefix: com.voidreader
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: KAJX3B69UF

packages:
  VoidReaderCore:
    path: .

targets:
  VoidReader:
    type: application
    platform: macOS
    sources:
      - path: App
        excludes:
          - "**/.DS_Store"
          - App/Resources
    resources:
      - path: App/Resources
        excludes:
          - "**/.DS_Store"
          - Assets.xcassets
    dependencies:
      - package: VoidReaderCore
      - target: VoidReaderQuickLook
        embed: true
        codeSign: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voidreader.app
        PRODUCT_NAME: VoidReader
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KAJX3B69UF
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: App/VoidReader.entitlements
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: VoidReader
        CFBundleShortVersionString: "0.2.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "14.0"
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Editor
            LSHandlerRank: Default
            LSItemContentTypes:
              - net.daringfireball.markdown
              - public.text
            NSDocumentClass: $(PRODUCT_MODULE_NAME).MarkdownDocument
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown

  VoidReaderQuickLook:
    type: app-extension
    platform: macOS
    sources:
      - path: QuickLookExtension
    dependencies:
      - package: VoidReaderCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voidreader.app.quicklook
        PRODUCT_NAME: VoidReaderQuickLook
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KAJX3B69UF
        SKIP_INSTALL: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: QuickLookExtension/VoidReaderQuickLook.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"
    info:
      path: QuickLookExtension/Info.plist
      properties:
        CFBundleDisplayName: VoidReader Quick Look
        CFBundleShortVersionString: "0.2.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "14.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.preview
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PreviewViewController
          NSExtensionAttributes:
            QLSupportsSearchableItems: false
            QLSupportedContentTypes:
              - net.daringfireball.markdown
              - public.plain-text

  VoidReaderTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/VoidReaderCoreTests
    dependencies:
      - target: VoidReader
      - package: VoidReaderCore

schemes:
  VoidReader:
    build:
      targets:
        VoidReader: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VoidReaderTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
