#!/usr/bin/env bash
# sweep.sh — size-sweep harness for threshold-cliff hunting.
#
# Runs a scenario against 10KB / 100KB / 1MB variants of a named fixture shape
# and emits a markdown p50/p95 table per signpost, assembled by
# `parse_signposts.py` from each trace's signpost-intervals XML.
#
# Orchestration only. Signpost extraction and table rendering live in Python
# (parse_signposts.py) — if you're tempted to parse XML in shell, stop.
#
# Usage:
#     scripts/perf/sweep.sh <scenario> <shape> [--save ARC_NAME] [--baseline PATH]
#
# Example:
#     scripts/perf/sweep.sh search-navigate wide-line-pathology \
#         --save add-performance-lab

set -euo pipefail

usage() {
    cat >&2 <<EOF
usage: $0 <scenario> <shape> [--save ARC_NAME] [--baseline BASELINE_JSON]

Runs <scenario> against <shape> at three sizes (10KB, 100KB, 1MB) and
emits a markdown p50/p95 table per named signpost.

Options:
    --save ARC_NAME     Write result to openspec/changes/<ARC_NAME>/findings/
                        sweep-<scenario>-<date>.md (stdout also prints).
                        Also writes a JSON snapshot alongside for future
                        --baseline comparisons.
    --baseline PATH     Prior sweep JSON snapshot to diff against; adds a
                        per-size Δp50 column.

Shapes (match names under Tests/VoidReaderCoreTests/Fixtures/):
    wide-line-pathology, many-small-blocks
EOF
    exit 2
}

if [[ $# -lt 2 ]]; then usage; fi

SCENARIO="$1"; SHAPE="$2"; shift 2
SAVE_ARC=""
BASELINE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --save)     SAVE_ARC="$2"; shift 2 ;;
        --baseline) BASELINE="$2"; shift 2 ;;
        -h|--help)  usage ;;
        *) echo "unknown flag: $1" >&2; usage ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FIXTURE_DIR="$REPO_ROOT/Tests/VoidReaderCoreTests/Fixtures"

SIZES=("10KB" "100KB" "1MB")
LABELED_ARGS=()

# Run scenario against each size variant, collecting signpost-intervals XML
# per size. run_scenario.sh writes both a time-profile XML and a
# signposts.xml; we only need the latter for p50/p95.
for SIZE in "${SIZES[@]}"; do
    FIXTURE="$FIXTURE_DIR/${SHAPE}-${SIZE}.md"
    if [[ ! -f "$FIXTURE" ]]; then
        echo "warning: missing fixture $FIXTURE — skipping $SIZE" >&2
        continue
    fi
    echo "[sweep] $SCENARIO @ $SIZE" >&2
    bash "$SCRIPT_DIR/run_scenario.sh" "$SCENARIO" --fixture "$FIXTURE" >/dev/null
    # Pick up the signposts XML that run_scenario.sh just wrote. Pattern
    # mirrors SIGNPOSTS_PATH in run_scenario.sh.
    LATEST_SIGNPOSTS="$(ls -1t "$REPO_ROOT/build/traces/${SCENARIO}-"*.signposts.xml 2>/dev/null | head -1)"
    if [[ -z "$LATEST_SIGNPOSTS" ]]; then
        echo "warning: no signposts XML produced for $SIZE — skipping" >&2
        continue
    fi
    LABELED_ARGS+=("--labeled" "${SIZE}:${LATEST_SIGNPOSTS}")
done

# Empty-sweep guard: without at least one trace we have nothing to table and
# nothing to save. Fail loudly rather than producing a headers-only doc that
# masquerades as a successful run.
if [[ ${#LABELED_ARGS[@]} -eq 0 ]]; then
    echo "error: no traces collected — check fixtures under $FIXTURE_DIR and run_scenario.sh output" >&2
    exit 1
fi

DATE_STR="$(date +%Y-%m-%d)"

# Build parse_signposts.py invocation. --emit-snapshot lets future runs of
# this script diff against today's numbers via --baseline.
PARSE_ARGS=("$SCRIPT_DIR/parse_signposts.py" "${LABELED_ARGS[@]}")
if [[ -n "$BASELINE" ]]; then
    if [[ ! -f "$BASELINE" ]]; then
        echo "error: --baseline file not found: $BASELINE" >&2
        exit 1
    fi
    PARSE_ARGS+=("--baseline" "$BASELINE")
fi

SNAPSHOT_PATH=""
if [[ -n "$SAVE_ARC" ]]; then
    OUT_DIR="$REPO_ROOT/openspec/changes/$SAVE_ARC/findings"
    mkdir -p "$OUT_DIR"
    SNAPSHOT_PATH="$OUT_DIR/sweep-${SCENARIO}-${DATE_STR}.snapshot.json"
    PARSE_ARGS+=("--emit-snapshot" "$SNAPSHOT_PATH")
fi

TABLE="$(python3 "${PARSE_ARGS[@]}")"

HEADER="# Sweep: $SCENARIO on $SHAPE ($DATE_STR)

Generated by \`scripts/perf/sweep.sh $SCENARIO $SHAPE\`.

## Dominant hot signature

_(fill in from manual review of the trace exports)_

## Interpretation

_(what this table says about where work is happening)_

## Chosen action

_(fix applied / deferred / accepted-with-justification)_

## Data

$TABLE
"

if [[ -n "$BASELINE" ]]; then
    HEADER="${HEADER}
Baseline compared: \`$BASELINE\`
"
fi

echo "$HEADER"

if [[ -n "$SAVE_ARC" ]]; then
    OUT_FILE="$OUT_DIR/sweep-${SCENARIO}-${DATE_STR}.md"
    echo "$HEADER" > "$OUT_FILE"
    echo "[sweep] saved to $OUT_FILE" >&2
    if [[ -n "$SNAPSHOT_PATH" && -f "$SNAPSHOT_PATH" ]]; then
        echo "[sweep] snapshot $SNAPSHOT_PATH" >&2
    fi
fi
